# Generated by Django 6.0 on 2025-12-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
