# Generated by Django 6.0 on 2025-12-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='我的博客', max_length=100, verbose_name='网站名称')),
                ('site_description', models.TextField(default='欢迎访问我的博客', verbose_name='网站描述')),
                ('site_keywords', models.CharField(default='博客,写作,分享', max_length=200, verbose_name='网站关键词')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_address', models.TextField(blank=True, verbose_name='联系地址')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook链接')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter链接')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub链接')),
                ('weibo_url', models.URLField(blank=True, verbose_name='微博链接')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
