# Generated by Django 6.0 on 2025-12-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('cpp', 'cpp'), ('java', 'java'), ('django', 'django')], default='technology', max_length=50, verbose_name='分类'),
        ),
    ]
