"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # 第三方应用
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'ckeditor',
    'taggit',
    'crispy_forms',
    'crispy_bootstrap5',
    'embed_video',
    'captcha',
    'rest_framework',
    'corsheaders',
    'haystack',
    'accounts',
    'api',
    'blog',
    'comments',
    'search',
    'widget_tweaks',

# 本地应用
#     'accounts.apps.AccountsConfig',
#     'blog.apps.BlogConfig',
#     'comments.apps.CommentsConfig',
#     'search.apps.SearchConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.context_processors.site_settings',
                'blog.context_processors.common_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 媒体文件
MEDIA_URL= '/media/'
MEDIA_ROOT= BASE_DIR / 'media'

# 默认主键
DEFAULT_AUTO_FIELD= 'django.db.models.BigAutoField'

# 自定义用户模型
AUTH_USER_MODEL= 'accounts.CustomUser'

# allauth 配置
SITE_ID= 1
ACCOUNT_EMAIL_REQUIRED= True
ACCOUNT_EMAIL_VERIFICATION= 'optional'
ACCOUNT_AUTHENTICATION_METHOD= 'username_email'
ACCOUNT_USERNAME_MIN_LENGTH= 3
LOGIN_REDIRECT_URL= '/'
LOGOUT_REDIRECT_URL= '/'
ACCOUNT_LOGOUT_ON_GET= True

# 认证后端
AUTHENTICATION_BACKENDS= [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS= "bootstrap5"
CRISPY_TEMPLATE_PACK= "bootstrap5"

# Redis 缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'django_cache'),
        'TIMEOUT': 300,
    }
}

# 会话配置
SESSION_ENGINE= "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS= "default"

# REST Framework
REST_FRAMEWORK= {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# CORS 配置
CORS_ALLOWED_ORIGINS= [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# 邮件配置
EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST= config('EMAIL_HOST')
EMAIL_PORT= config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS= True
EMAIL_HOST_USER= config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD= config('EMAIL_HOST_PASSWORD')

# CKEditor 配置
CKEDITOR_CONFIGS= {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source', 'CodeSnippet']
        ],
        'height': 300,
        'width': '100%',
    },
}

# Haystack 搜索
HAYSTACK_CONNECTIONS= {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SIGNAL_PROCESSOR= 'haystack.signals.RealtimeSignalProcessor'

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#验证码设置
CAPTCHA_LETTER_ROTATION = None
CAPTCHA_NOISE_FUNCTIONS = ('captcha.helpers.noise_null',)
CAPTCHA_CHALLENGE_FUNCTIONS = ('captcha.helpers.math_challenge',)
CAPTCHA_TIMEOUT = 5

# settings.py - 在文件末尾添加以下配置

# 网站设置
SITE_NAME = config('SITE_NAME', default='我的博客')
SITE_DESCRIPTION = config('SITE_DESCRIPTION', default='欢迎访问我的博客')
SITE_KEYWORDS = config('SITE_KEYWORDS', default='博客,写作,分享')
SITE_URL = config('SITE_URL', default='http://localhost:8000')
CONTACT_EMAIL = config('CONTACT_EMAIL', default='contact@example.com')
CONTACT_PHONE = config('CONTACT_PHONE', default='')
CONTACT_ADDRESS = config('CONTACT_ADDRESS', default='')
FACEBOOK_URL = config('FACEBOOK_URL', default='')
TWITTER_URL = config('TWITTER_URL', default='')
GITHUB_URL = config('GITHUB_URL', default='')
WEIBO_URL = config('WEIBO_URL', default='')
GOOGLE_ANALYTICS_ID = config('GOOGLE_ANALYTICS_ID', default='')

# 文件上传配置
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# 安全配置（生产环境需要调整）
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session配置
SESSION_COOKIE_AGE = 1209600  # 2周
SESSION_SAVE_EVERY_REQUEST = True

# CSRF配置
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# CKEditor上传配置
CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}